//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizedApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizedApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferred culture is : en.
        /// </summary>
        public static string HomePage_CurrentCultureText {
            get {
                return ResourceManager.GetString("HomePage_CurrentCultureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Xamarin.Forms !.
        /// </summary>
        public static string HomePage_GreetingsText {
            get {
                return ResourceManager.GetString("HomePage_GreetingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another culture.
        /// </summary>
        public static string HomePage_SelectCultureText {
            get {
                return ResourceManager.GetString("HomePage_SelectCultureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        public static string SettingsPage_en_LanguageDescriptionText {
            get {
                return ResourceManager.GetString("SettingsPage_en_LanguageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingsPage_en_LanguageText {
            get {
                return ResourceManager.GetString("SettingsPage_en_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string SettingsPage_en_US_LanguageDescriptionText {
            get {
                return ResourceManager.GetString("SettingsPage_en_US_LanguageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingsPage_en_US_LanguageText {
            get {
                return ResourceManager.GetString("SettingsPage_en_US_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGION FORMAT EXAMPLE.
        /// </summary>
        public static string SettingsPage_FormatSectionText {
            get {
                return ResourceManager.GetString("SettingsPage_FormatSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string SettingsPage_fr_LanguageText {
            get {
                return ResourceManager.GetString("SettingsPage_fr_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingsPage_LanguageFormatText {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGES.
        /// </summary>
        public static string SettingsPage_LanguageSectionText {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPage_TitleText {
            get {
                return ResourceManager.GetString("SettingsPage_TitleText", resourceCulture);
            }
        }
    }
}
